CREATE TABLE IF NOT EXISTS pictures (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	user_id INTEGER NOT NULL,
	image_path TEXT NOT NULL,
	caption TEXT,
	created_at DATETIME DEFAULT CURRENT_TIMESTAMP,

	FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);