CREATE TABLE IF NOT EXISTS sessions (
    id INTEGER PRIMARY KEY,
    session_id TEXT NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
   
    FOREIGN KEY (id) REFERENCES login_users(id) ON DELETE CASCADE
)